"""add_conversations_and_conversation_turns

Revision ID: 0e785d094cbd
Revises: 06e4945f3618
Create Date: 2026-02-25 22:11:54.323763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e785d094cbd'
down_revision: Union[str, Sequence[str], None] = '06e4945f3618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print(f"[PY] 0e785d094cbd_add_conversations_and_conversation_turns.py | upgrade | L21: Logic flowing")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], name=op.f('fk_conversations_org_id_organisations')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_conversations_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('proposal_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_turns_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns'))
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    print(f"[PY] 0e785d094cbd_add_conversations_and_conversation_turns.py | downgrade | L52: Antigravity active")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_id'))

    op.drop_table('conversation_turns')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    # ### end Alembic commands ###