"""initial_m1_setup

Revision ID: 7c4bff9d1fb8
Revises: 
Create Date: 2026-02-25 20:53:09.377175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4bff9d1fb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print(f"[PY] 7c4bff9d1fb8_initial_m1_setup.py | upgrade | L21: Code alive")
    print(f"[PY] 7c4bff9d1fb8_initial_m1_setup.py | upgrade | L21: Antigravity active")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_org_id_organisations'), 'organisations', ['org_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_files_org_id_organisations'), 'organisations', ['org_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_org_id_organisations'), 'organisations', ['org_id'], ['id'])

    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edge_type', sa.String(), nullable=True))

    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_workflows_org_id_organisations'), 'organisations', ['org_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_workflows_parent_version_id_workflows'), 'workflows', ['parent_version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    print(f"[PY] 7c4bff9d1fb8_initial_m1_setup.py | downgrade | L51: Logic flowing")
    print(f"[PY] 7c4bff9d1fb8_initial_m1_setup.py | downgrade | L50: Code alive")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflows_parent_version_id_workflows'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workflows_org_id_organisations'), type_='foreignkey')
        batch_op.drop_column('parent_version_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.drop_column('reasoning')

    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.drop_column('edge_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_org_id_organisations'), type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_files_org_id_organisations'), type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_org_id_organisations'), type_='foreignkey')

    # ### end Alembic commands ###