"""add_domain_packs

Revision ID: b0d206ef50d7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 20:01:21.669459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d206ef50d7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print(f"[PY] b0d206ef50d7_add_domain_packs.py | upgrade | L21: Code alive")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], name=op.f('fk_domain_packs_org_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_packs'))
    )
    with op.batch_alter_table('domain_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_packs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    print(f"[PY] b0d206ef50d7_add_domain_packs.py | downgrade | L40: Logic flowing")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_packs_id'))

    op.drop_table('domain_packs')
    # ### end Alembic commands ###